site_name: Rosa Channel Service
site_description: Documentação técnica do Rosa Channel Service
site_url: https://example.local/rosa-channel-service
repo_name: rosa-channel-service
repo_url: https://example.local/rosa-channel-service

theme:
  name: material
  language: pt-BR

nav:
  - Início: docs/get_start.md
  - Stack: docs/stacks.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
